### ISSUE TITLE
Issue with unserialize function

### ISSUE THREAD

**Issue by gabkk** [akashkaushik33/node-wp-authenticator#1]
Hello
I am using your package wp-auth version:
` "wp-auth": "^1.0.1"`
which is quite useful but there is an issue with the current version of phpjs.unserialize.
When we are using your function sanitizeValue("nickname").

ex:
```
sanitizeValue("nickname"); 
returns null
```
```
sanitizeValue("test"); 
throw an error
```

You are only testing the case when an error is throw and unfortunately i am sending "nickname" so null is serialized and the wrong request is sent to my mysql DB

It seems to be fixed in the last version of [unserialize](https://locutus.io/php/var/unserialize/)
sanitizeValue("nickname");
return false
sanitizeValue("undefined");
return false

Instead of checking if an error is throw you will only have to check if the return is false.

**Comment by gabkk** [comment]
I opened a pull request if you want to test it 
[Pull request 2](https://github.com/akashkaushik33/node-wp-authenticator/pull/2#pullrequestreview-498381350)

**Comment by akashkaushik33** [comment]
Hey @gabkk , thanks for letting me know the issue and creating the pull request. I'll check it out later in the evening and update the package in npm.

**Comment by akashkaushik33** [comment]
#2   Merged your pull request and updated the indentation. Closing this issue now. 
Version 1.0.2 is published with the updated code https://www.npmjs.com/package/wp-auth
