### ISSUE TITLE
setUserMeta queries are missing a space 

### ISSUE THREAD

**Issue by avdan** [akashkaushik33/node-wp-authenticator#3]
Hello,
I've been trying to use this package and noticed that there is an issue with the setUserMeta function. Two space characters are missing so the queries fail:

Line 147:
`this.db.query(
    'delete from' +
      this.table_prefix +
      "usermeta where meta_key = '" +
      sanitizeValue(key) +
      "' and user_id = " +
      parseInt(id)
  );`

is missing a space after "from". Should be:

`this.db.query(
    'delete from ' +
      this.table_prefix +
      "usermeta where meta_key = '" +
      sanitizeValue(key) +
      "' and user_id = " +
      parseInt(id)
  );`

Line 155:
` this.db.query(
    'insert into' +
      this.table_prefix +
      "usermeta (meta_key, user_id, meta_value) VALUES('" +
      sanitizeValue(key) +
      "', " +
      parseInt(id) +
      ", '" +
      sanitized_value +
      "')"
  );
`
is missing a space after "from". Should be:

`this.db.query(
    'insert into ' +
      this.table_prefix +
      "usermeta (meta_key, user_id, meta_value) VALUES('" +
      sanitizeValue(key) +
      "', " +
      parseInt(id) +
      ", '" +
      sanitized_value +
      "')"
  );`

Apart from that 

this.meta_cache[id][key] = value; triggers an error:  _"TypeError: Cannot set property 'my_key' of undefined"_
Because this.meta_cache[id] should be initialized with this.meta_cache[id] = {}.

**Comment by akashkaushik33** [comment]
@avdan  Thanks for reporting the issue, will fix this in the next update.

**Comment by akashkaushik33** [comment]
@avdan This is fixed now in version 1.0.5 along with some other updates.
