### ISSUE TITLE
Disable console log if non development process?

### ISSUE THREAD

**Issue by isuke01** [akashkaushik33/node-wp-authenticator#4]
Hey,

I just tried it out, and everything works great, but Console log just bother me, since user can see many things from console log, especially during error with connection thne he will see too much. :)

**Comment by akashkaushik33** [comment]
Hey @isuke01 , thanks for letting me know. I will soon publish a version with logs visible in debug mode only.

**Comment by isuke01** [comment]
@akashkaushik33 Thanks :)
