### ISSUE TITLE
Getting basic information about the user

### ISSUE THREAD

**Issue by sr258** [akashkaushik33/node-wp-authenticator#8]
Is it possible to somehow get the information from the `users` table as described here? https://developer.wordpress.org/plugins/users/working-with-user-metadata/

The WP docs say that these columns are part of this tabel: `: ID, user_login, user_pass, user_nicename, user_email, user_url, user_registered, user_activation_key, user_status, display_name`

It looks like wp-auth can only get the user metadata and not the basic information from the user table.

**Comment by akashkaushik33** [comment]
As of right now, we only use the user meta table. But once auth is successful, we can get infomration from users table as well with the user id we get in response from auth fn.
For that we may need to add a new function which does this.
